### ISSUE TITLE
Doubt about the model

### ISSUE THREAD

**Issue by KevinPedroza** [pecu/FinancialVision#5]
Hi good afternoon, i am starting a thesis at the university about finance market. And i want to know if there is a jupyter or github where i can use the model the generates the data as a reference for my thesis.

**Comment by pecu** [comment]
The FinancialVision repository is including all our papers. We will append more projects recently.
There are two papers in the repository, and which one do you use as the reference?

https://github.com/pecu/FinancialVision/tree/master/Data%20Augmentation%20For%20Deep%20Candlestick%20Learner

https://github.com/pecu/FinancialVision/tree/master/Explainable%20Deep%20Convolutional%20Candlestick%20Learner

Please cite the project's Arxiv directly.

**Comment by KevinPedroza** [comment]
Thank you for replying me, I am use the second one as a reference, the explainable deep convolutional. 
But what there is missing to me is the model to generate the data from the symbol EURUSD

**Comment by bigmoumou** [comment]
We have uploaded the relative rule-based code, but it just a part of the full process. The remaining part still needs some time since it's a mass.

The code is in this [subfolder](https://github.com/pecu/FinancialVision/tree/master/Encoding%20candlesticks%20as%20images%20for%20patterns%20classification%20using%20convolutional%20neural%20networks). `rulebase.py` already includes all crucial rule-based code and multiprocess speedup. It just lacks the GAF encoding and sampling process.

**Comment by KevinPedroza** [comment]
Thank you very much!
